Fix pipenv

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -168,9 +168,23 @@ jobs:
       - name: CLI test
         run: |
           cd testing/sample_project
-          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
-          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
-          ./assert.sh
+          cp Pipfile.template Pipfile
+          echo "${PYTHON_VERSION:?}" >> Pipfile
+          pipenv uninstall tupper
+          set +e
+          pipenv run python -m tupper
+          returned=$?
+          set -e
+          if [[ "${returned}" != "1" ]]; then
+            echo "Expected tupper execution to fail gracefully: ${returned}"
+            exit 1
+          fi
+          cauth pipenv install
+          pipenv run python -m tupper
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          PYTHON_VERSION: ${{ matrix.python-version }}
 
   publish:
     # Publish only when tagging.
